# .pages.yml
media:
  input: src/images
  output: /images

content:
  - name: dates
    label: Prochains événements
    type: collection
    path: "src/_data/dates"
    fields:
      - name: date
        label: Date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: description
        label: Description
        type: string
        required: true
      - name: lieu
        label: Lieu
        type: text
        required: true
  - name: seo
    label: Moteurs de recherche (SEO)
    type: file
    path: "src/_data/site.json"
    fields:
      - name: name
        label: Nom du site
        type: string
        required: true
      - name: title
        label: Titre SEO
        type: string
        required: true
      - name: description
        label: Description SEO
        type: text
        required: true
      - name: url
        label: URL du site
        type: string
        required: true
      - name: ogImage
        label: Image Open Graph (chemin)
        type: string
        help: "Chemin vers l'image (ex: /images/og.png)"
        required: true
