# .pages.yml
media:
  input: src/images
  output: /images

content:
  - name: dates
    label: Prochaines dates
    type: file
    path: "src/_data/dates.json"
    fields:
      - name: events
        label: Événements
        type: list
        fields:
          - name: description
            label: Description
            type: string
            required: true
          - name: date
            label: Date (YYYY-MM-DD)
            type: string
            required: true
          - name: lieu
            label: Lieu
            type: text
            required: true
  - name: seo
    label: Moteurs de recherche (SEO)
    type: file
    path: "src/_data/site.json"
    fields:
      - name: name
        label: Nom du site
        type: string
        required: true
      - name: title
        label: Titre SEO
        type: string
        required: true
      - name: description
        label: Description SEO
        type: text
        required: true
      - name: url
        label: URL du site
        type: string
        required: true
      - name: ogImage
        label: Image Open Graph (chemin)
        type: string
        help: "Chemin vers l'image (ex: /images/og.png)"
        required: true
