# .pages.yml
media:
  input: src/images
  output: /images

content:
  - name: SEO
    label: Optimisation pour les moteurs de recherche
    type: file
    path: "src/_data/site.json"
    fields:
      - name: name
        label: Nom du site
        type: string
        required: true
      - name: title
        label: Titre SEO
        type: string
        required: true
      - name: description
        label: Description SEO
        type: text
        required: true
      - name: url
        label: URL du site
        type: string
        required: true
      - name: ogImage
        label: Image Open Graph (chemin)
        type: string
        help: "Chemin vers l'image (ex: /images/og.png)"
        required: true
